### ISSUE TITLE
Remove (or comment) Serial.printf messages in mscBegin methode (USBFat.h)

### ISSUE THREAD

**Issue by BOBILLIER** [wwatson4506/UsbMscFat#12]
Please in a future version, can you remove Serial.printf comment in mscBegin or place them with debug argument to avoid see them in our code.

**Comment by wwatson4506** [comment]
BOBILLIER,

We are still developing this code so the Serial.printf's and println's will stay for now. You can alway's comment them out in your copy of this library:)
